version: '2'
services:
    interview:
        build: .
        command: python manage.py runserver 0.0.0.0:8006
        volumes:
            - .:/code
        ports:
            - "8006:8006"
        network_mode: bridge